# Generated by Django 4.1.3 on 2022-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="edu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=100)),
                ("University_name", models.CharField(max_length=200)),
                ("date_passed", models.DateField()),
                ("course_duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                ("notice_period_days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email_id", models.CharField(max_length=50)),
                ("phone", models.BigIntegerField()),
                ("address", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=150)),
                ("experience_years", models.IntegerField()),
            ],
        ),
    ]
